### ISSUE TITLE
Search function is not working

### ISSUE THREAD

**Issue by smitk85143** [digitalmethodsinitiative/itunes-app-scraper#10]
I think it require connect iTunes store.

**Comment by dale-wahl** [comment]
Sorry you are having difficulties. I just tested on our server and I am able to perform searches. Perhaps you could provide some more details (how exactly are you using the tool, what sort of environment are you using, how did you install it. etc.). It does indeed need to be about to connect to the iTunes store and extract data from specific links.

You can find more here to see exactly how it does so:
https://github.com/digitalmethodsinitiative/itunes-app-scraper/blob/master/itunes_app_scraper/scraper.py

**Comment by smitk85143** [comment]
Okay, It solved.

Thank you for your response.
