### ISSUE TITLE
KeyError on BadRequest in get_app_details

### ISSUE THREAD

**Issue by mslusarczyk** [digitalmethodsinitiative/itunes-app-scraper#5]
Call to https://itunes.apple.com/lookup?id=283654982364450862376 results in 
```
{"errorMessage": "Invalid value(s) for key(s): [itunesId]",
    "queryParameters": {
        "output": "json",
        "callback": "A javascript function to handle your search results",
        "country": "ISO-2A country code",
        "limit": "The number of search results to return",
        "term": "A search string",
        "lang": "ISO-2A language code"
    }
}
```

which is parsable JSON so works [here](https://github.com/digitalmethodsinitiative/itunes-app-scraper/blob/master/itunes_app_scraper/scraper.py#L180) but fails [here](https://github.com/digitalmethodsinitiative/itunes-app-scraper/blob/master/itunes_app_scraper/scraper.py#L191) with KeyError.

Draft of the fix https://github.com/digitalmethodsinitiative/itunes-app-scraper/pull/6

**Comment by dale-wahl** [comment]
Accepted [pull request](https://github.com/digitalmethodsinitiative/itunes-app-scraper/pull/6)
