### ISSUE TITLE
Language mismatch

### ISSUE THREAD

**Issue by adtisch** [digitalmethodsinitiative/itunes-app-scraper#8]
The following code:

`from itunes_app_scraper.scraper import AppStoreScraper
import pandas as pd

scraper = AppStoreScraper()
results = scraper.get_app_ids_for_query("mental health", page=2, num=50, country = 'us', lang='en')
app_details = scraper.get_multiple_app_details(results, sleep=0, lang = 'en')
df = pd.DataFrame(app_details)`

returns some of the app descriptions in a language that is not english. I was able to fix this issue by forking the page and hard-coding lines 190 to 192 of scraper.py to be:
`			url = "https://itunes.apple.com/lookup?%s=%s&country=%s&entity=software&timestamp=%s" % (id_field, app_id, 'us', timestamp)
		else:
			url = "https://itunes.apple.com/lookup?%s=%s&country=%s&entity=software" % (id_field, app_id, 'us')`

**Comment by dale-wahl** [comment]
Thanks for reporting, @adtisch, I see the confusion. If you check the doc strings for ` scraper.get_multiple_app_details()`, it states ":param str lang: Dummy argument for compatibility. Unused." The `lang` parameter is only for compatibility with our Google app store scraper as their urls use language as a parameter. If you change your line from `scraper.get_multiple_app_details(results, sleep=0, lang = 'en')` to  `scraper.get_multiple_app_details(results, sleep=0, country='us')`, it will do exactly what you hard-coded.

Perhaps I should look at a way to remove the `lang` parameter entirely; not sure why this methodology was chosen.

**Comment by dale-wahl** [comment]
Not fixing. It is necessary for the https://github.com/digitalmethodsinitiative/app-scrapers to work as currently designed.
